### ISSUE TITLE
Postgres version mismatch

### ISSUE THREAD

**Issue by victorhazbun** [rails/devcontainer#58]
I'm getting the following error while using `postgres:16` in `compose.yaml` and `ghcr.io/rails/devcontainer/features/postgres-client` in `devcontainer.json`

```
vscode ➜ /workspaces/rideshare (main) $ pg_dump --schema-only --no-privileges --no-owner --file /workspaces/rideshare/db/structure.sql --clean --if-exists --schema=rideshare $DB_URL
pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 16.4 (Debian 16.4-1.pgdg120+2); pg_dump version: 15.8 (Debian 15.8-0+deb12u1)
```

Notice server version is 16.4 but psql version is 15.8, I believe this is an issue on `ghcr.io/rails/devcontainer/features/postgres-client`. I tried the `version` option but got the same error.

```
vscode ➜ /workspaces/rideshare (main) $ psql $DB_URL
psql (15.8 (Debian 15.8-0+deb12u1), server 16.4 (Debian 16.4-1.pgdg120+2))
WARNING: psql major version 15, server major version 16.
         Some psql features might not work.
```

devcontainer.json

```json
{
  "name": "rideshare",
  "dockerComposeFile": "compose.yaml",
  "service": "rails-app",
  "workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}",
  "features": {
    "ghcr.io/devcontainers/features/github-cli:1": {},
    "ghcr.io/rails/devcontainer/features/postgres-client": {}
  },
  "containerEnv": {
  },
  "forwardPorts": [
    3000,
    5432,
    6379
  ],
  "postCreateCommand": "bin/setup"
}

```

compose.yaml

```yaml
name: "rideshare"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    command: sleep infinity

    depends_on:
    - selenium
    - redis
    - postgres

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

  redis:
    image: redis:7.2
    restart: unless-stopped
    volumes:
    - redis-data:/data

  postgres:
    image: postgres:16
    restart: unless-stopped
    networks:
    - default
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

volumes:
  redis-data:
  postgres-data:

```
